# Generated by Django 4.0.6 on 2022-07-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=100, unique=True)),
                ('account_id', models.CharField(max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=50)),
            ],
        ),
    ]
